packages:
  - libs/*
  - plugins/*
includeWorkspaceRoot: true
allowBuilds:
  cpu-features: true
  esbuild: true
  oxc-resolver: true
  protobufjs: true
  ssh2: true
  unrs-resolver: true
overrides:
  "unrs-resolver": "1.11.1"
