const SEPARATOR = "[._-]";
const IDENTITY_CHARACTER = "[0-9A-Za-z_-]";
const IDENTIFIER = `${IDENTITY_CHARACTER}+`;

export const REGULAR_EXPRESSIONS = {
  SEPARATOR,
  IDENTITY_CHARACTER,
  PRERELEASE: `${IDENTIFIER}(?:\\.${IDENTIFIER})*`,
  BUILD: `${IDENTIFIER}(?:\\.${IDENTIFIER})*`,
};
