name: Release

on:
  push:
    branches:
      - main
      - next
      - "*.x"

permissions:
  contents: read

env:
  FORCE_COLOR: 1
  NPM_CONFIG_COLOR: always
  YARN_ENABLE_IMMUTABLE_INSTALLS: false
  NODE_OPTIONS: "--max-old-space-size=4096 --max-semi-space-size=4096"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: pnpm
      - run: corepack enable
      - run: pnpm install
      - run: pnpm run knip
      - run: pnpm run lint
      - run: pnpm --workspace-concurrency=1 --recursive run type-check

  test:
    strategy:
      matrix:
        node-version:
          - 22
          - lts/*
          - latest
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - uses: actions/checkout@v4
      - run: git config --global user.name github-actions
      - run: git config --global user.email github-actions@github.com
      - uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - run: corepack enable
      - run: pnpm install
      - run: pnpm --workspace-concurrency=1 --recursive run test:cov run
      - run: pnpm --workspace-concurrency=1 --recursive run test:e2e run

  release:
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: pnpm
      - run: corepack enable
      - run: npm config set "//registry.npmjs.org/:_authToken" "${NPM_TOKEN}" # pnpm config set is broken
        env:
          NPM_TOKEN: ${{ secrets.LETS_RELEASE_NPM_TOKEN }}
      - run: pnpm install
      - run: pnpm --workspace-concurrency=1 --recursive run build
      - run: pnpm vite-node src/cli.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
