name: Release

on:
  push:
    branches:
      - main
      - next
      - "*.x"

permissions:
  contents: read

env:
  FORCE_COLOR: 1
  NPM_CONFIG_COLOR: always
  YARN_ENABLE_IMMUTABLE_INSTALLS: false
  NODE_OPTIONS: "--max-old-space-size=4096 --max-semi-space-size=4096"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets:
      docker-token: ${{ secrets.LETS_RELEASE_DOCKER_TOKEN }}

  release:
    needs: test
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: latest
          check-latest: true
          cache: pnpm
      - run: npm install -g corepack@latest
      - run: corepack enable
      - run: npm config set scope lets-release --global
      - run: npm config set "//registry.npmjs.org/:_authToken" "${NPM_TOKEN}" # pnpm config set is broken
        env:
          NPM_TOKEN: ${{ secrets.LETS_RELEASE_NPM_TOKEN }}
      - run: pnpm install
      - run: pnpm --recursive --workspace-concurrency=1 run build
      - run: pnpm vite-node src/cli.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
